# Numpy

In [8]:
import os
os.getcwd()

'C:\\Users\\uAndo'

In [9]:
os.chdir('C:\\Users\\uAndo\\Downloads')

In [10]:
os.getcwd()

'C:\\Users\\uAndo\\Downloads'

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [31]:
import numpy as np
data = np.loadtxt('data_minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1)
print(data[0:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [22]:
np.set_printoptions(suppress=True)
print('Среднее значение 2го и 3го столбцов:', np.mean(data[:,1:], axis=0))
print('Минимум 2го и 3го столбцов:', np.min(data[:,1:], axis=0))
print('Максимум 2го и 3го столбцов:', np.max(data[:,1:], axis=0))
print('Медиана 2го и 3го столбцов:', np.median(data[:,1:], axis=0))

Среднее значение 2го и 3го столбцов: [21601.00169     9.05528]
Минимум 2го и 3го столбцов: [0 1]
Максимум 2го и 3го столбцов: [2147483647         39]
Медиана 2го и 3го столбцов: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [6]:
q = np.quantile(data[:,1], q = 0.75)
data[:,1] = data[:,1].clip(max = q)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [32]:
print('Количество рецептов с продолжительностью, равной 0: ', np.sum(data[:,1] == 0))
data[:,1] [data[:,1] == 0] = 1

Количество рецептов с продолжительностью, равной 0:  479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [26]:
print('Количество уникальных рецептов в датасете: ', len(np.unique(data, axis = 1)))

Количество уникальных рецептов в датасете:  100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [29]:
print('Кол-во различных ингредиентов датасета: ', len(np.unique(data[:,2])))
print('Значения различных ингредиентов датасета: ', np.unique(data[:,2]))

Кол-во различных ингредиентов датасета:  37
Значения различных ингредиентов датасета:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [25]:
ingred5_data = data[data[:,2] <= 5]

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [33]:
print('Максимальное кол-во ингредиентов на 1 мин. рецепта: ', max(data[:,2] / data[:,1]))

Максимальное кол-во ингредиентов на 1 мин. рецепта:  24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [38]:
print('Cреднее кол-во ингредиентов для топ-100 рецептов с max продолжительностью:', np.mean(data[data[:,1].argsort()][::-1][0:100][:,2]))

Cреднее кол-во ингредиентов для топ-100 рецептов с max продолжительностью: 9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [26]:
print(data[np.random.choice(data.shape[0], 10)])

[[ 96411     15      8]
 [ 51704     35      9]
 [230255      1      2]
 [ 41185     15      6]
 [502510     60     15]
 [394633     45     16]
 [317680     30      5]
 [231748     45     10]
 [ 34071    110      8]
 [ 35896     79     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [47]:
print('% рецептов, кол-во ингредиентов в которых < среднего:', len(data[data[:,2] < np.mean(data[:,2])]) / len(data[:,2]) * 100)

% рецептов, кол-во ингредиентов в которых < среднего: 58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [28]:
result = (data[:,1] <= 20) & (data[:,2] <= 5).astype('int32')
simple_recipes = np.insert(data, 3, result, axis = 1)
print(simple_recipes)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [29]:
print('% "простых" рецептов в датасете:', len(simple_recipes[simple_recipes[:,3] == 1]) / len(simple_recipes) * 100)

% "простых" рецептов в датасете: 9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [30]:
short = data[data[:,1] < 10]
medium = data[(data[:,1] >= 10) & (data[:,1] < 20)]
long = data[data[:,1] > 20]
max_size = min(map(len, [short, medium, long]))
a = np.vstack(([short[:max_size,:]], [medium[:max_size,:]], [long[:max_size,:]]))
print(a.shape)

(3, 7588, 3)
